### PR TITLE
EDA code version 1

### PR DESCRIPTION
**Pull request by razon7**

### CODE REVIEW

**Comment by dschul01** [comment]
Great work on this Rajkala!

**Review by dschul01 — APPROVED** [review]
Great work on this and lots of good plots to choose from for final visuals!

**Review by Kelfang — APPROVED** [review]
This looks awesome! Great detail. 
I have just one recommendation on the following code: 
fig,ax = plt.subplots(1,figsize=(20,10))
sns.boxplot( y=df["Early_Career_Pay"], x=df["State"] )
**Add this line of code to rotate the state names so they can be read.**
plt.xticks(rotation=45, ha="right")

**Review by JumokeHicok — APPROVED** [review]
Looks good!!

**Pull request merged**
